language: java
install: true

jdk:
  - oraclejdk8

services:
  - docker

script:
  - ./gradlew --refresh-dependencies clean build

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: develop